name: ArtisanTony
favicon: null
layout_spectrum: 0.92115
typography_spectrum: 0.57912
title: ArtisanTony on the Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#313131'
    - '#5f5f5f'
    - '#8f8f8f'
  brandStrength: 0.75
  lightness: 0.5851785412523896
  saturation: 0.9384386155288666
  rhythmicContrast: 0.10890519595704973
purpose: []
